CREATE TABLE Users (
    UserID INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    Email NVARCHAR(100) NOT NULL UNIQUE,
    CreatedAt DATETIME DEFAULT GETDATE()
);

CREATE TABLE Devices (
    DeviceID INT IDENTITY(1,1) PRIMARY KEY,
    UserID INT NOT NULL,
    DeviceName NVARCHAR(100),
    OS NVARCHAR(100),
    CPU NVARCHAR(100),
    RAM INT,
    Storage NVARCHAR(100),
    CreatedAt DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

CREATE TABLE NetworkInfo (
    NetworkID INT IDENTITY(1,1) PRIMARY KEY,
    DeviceID INT NOT NULL,
    MACAddress NVARCHAR(50),
    IPAddress NVARCHAR(50),
    ConnectionType NVARCHAR(50),
    UpdatedAt DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (DeviceID) REFERENCES Devices(DeviceID)
);
